hf upload DanielLevenstein/HelmNet_Image_Classification model/HelmNet_Image_Classification.v1.h5
hf upload DanielLevenstein/HelmNet_Image_Classification model/HelmNet_Image_Classification.v2.h5
hf upload DanielLevenstein/HelmNet_Image_Classification model/HelmNet_Image_Classification.v2.h5
hf upload DanielLevenstein/HelmNet_Image_Classification model/HelmNet_Image_Classification.v3.h5
hf upload DanielLevenstein/HelmNet_Image_Classification validation_results.md